smb_server: "NAS"
smb_share: "Media"       # \\NAS\Media
smb_user: "nasuser"
smb_pass: "naspassword"

media_local_path: "/srv/media"
media_mount_path: "/mnt/nas_media"

run_sync_as_service: true     # or false to use cron
sync_time: "00:00"            # only used with systemd timers

